#!/usr/bin/env bash
# build-stack.sh — bring up the Docker side of hermes-stack from scratch.
#
#   aitools-backends (pgvector/pgvector:pg18 + redis) -> aitools-services
#   (LiteLLM + Honcho api/deriver), joined by external network aitools-net.
#
# Idempotent where reasonable: re-running reuses an existing network, reuses
# already-generated DB passwords (so volumes/keys keep matching), and
# regenerates LiteLLM virtual keys (needed after a PG major rebuild — see
# README gotcha #4). Requires only secrets.env.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO"

SECRETS="$REPO/secrets.env"
[ -f "$SECRETS" ] || { echo "FATAL: $SECRETS not found. cp secrets.env.example secrets.env and fill it in." >&2; exit 1; }
# shellcheck disable=SC1090
set -a; . "$SECRETS"; set +a

: "${OPENROUTER_API_KEY:?OPENROUTER_API_KEY required in secrets.env}"
: "${VOYAGE_API_KEY:?VOYAGE_API_KEY required in secrets.env}"

BK_ENV="$REPO/aitools-backends/.env"
SV_ENV="$REPO/aitools-services/.env"
KEYS="$REPO/aitools-services/keys.generated.env"
HONCHO_PIN="8fcbb54a49292341dba79d606ee332c50778429b"   # plastic-labs/honcho pinned commit

dc() { docker compose --env-file "$1" "${@:2}"; }
log() { printf '\n=== %s ===\n' "$*"; }

# ---------------------------------------------------------------------------
log "1. external network aitools-net"
docker network create aitools-net 2>/dev/null || echo "aitools-net exists"

# ---------------------------------------------------------------------------
log "2. aitools-backends/.env (generate passwords once; reuse if present)"
if [ -f "$BK_ENV" ]; then
  echo "reusing existing $BK_ENV (keeps matching the pg volume)"
else
  cat > "$BK_ENV" <<EOF
# Generated by build-stack.sh — gitignored. DB role passwords.
POSTGRES_SUPERPASS=$(openssl rand -hex 16)
HONCHO_DB_PASSWORD=$(openssl rand -hex 16)
LITELLM_DB_PASSWORD=$(openssl rand -hex 16)
EOF
  echo "wrote $BK_ENV"
fi
HONCHO_DB_PASSWORD="$(grep '^HONCHO_DB_PASSWORD=' "$BK_ENV" | cut -d= -f2-)"
LITELLM_DB_PASSWORD="$(grep '^LITELLM_DB_PASSWORD=' "$BK_ENV" | cut -d= -f2-)"

# ---------------------------------------------------------------------------
log "3. aitools-backends up + wait pg/redis healthy"
dc "$BK_ENV" -f aitools-backends/compose.yaml up -d
for i in $(seq 1 30); do
  s=$(docker inspect -f '{{.State.Health.Status}}' aitools-pg 2>/dev/null || echo none)
  r=$(docker inspect -f '{{.State.Health.Status}}' aitools-redis 2>/dev/null || echo none)
  [ "$s" = healthy ] && [ "$r" = healthy ] && { echo "pg+redis healthy"; break; }
  sleep 3
  [ "$i" = 30 ] && { echo "FATAL: backends not healthy (pg=$s redis=$r)" >&2; exit 1; }
done

# ---------------------------------------------------------------------------
log "4. aitools-services/.env (propagate DB passwords + provider keys)"
LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-}"
[ -n "$LITELLM_MASTER_KEY" ] || LITELLM_MASTER_KEY="sk-$(openssl rand -hex 24)"
cat > "$SV_ENV" <<EOF
# Generated by build-stack.sh — gitignored.
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY
LITELLM_DB_PASSWORD=$LITELLM_DB_PASSWORD
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
VOYAGE_API_KEY=$VOYAGE_API_KEY
HONCHO_DB_PASSWORD=$HONCHO_DB_PASSWORD
EOF
echo "wrote $SV_ENV (LITELLM_DB_PASSWORD matched from aitools-backends)"

# ---------------------------------------------------------------------------
log "5. honcho-src @ pinned commit $HONCHO_PIN"
if [ -d "$REPO/aitools-services/honcho-src" ] && [ -f "$REPO/aitools-services/honcho-src/Dockerfile" ]; then
  echo "honcho-src already present (gitignored build context) — reusing"
else
  git clone https://github.com/plastic-labs/honcho "$REPO/aitools-services/honcho-src"
  git -C "$REPO/aitools-services/honcho-src" checkout "$HONCHO_PIN"
  rm -rf "$REPO/aitools-services/honcho-src/.git"
  echo "honcho-src pinned @ $HONCHO_PIN (.git removed for reproducibility)"
fi

# ---------------------------------------------------------------------------
log "6. aitools-litellm up + wait healthy (litellm-database auto-runs prisma migrations)"
dc "$SV_ENV" -f aitools-services/compose.yaml up -d aitools-litellm
for i in $(seq 1 36); do
  h=$(docker inspect -f '{{.State.Health.Status}}' aitools-litellm 2>/dev/null || echo none)
  [ "$h" = healthy ] && { echo "litellm healthy"; break; }
  sleep 5
  [ "$i" = 36 ] && { echo "FATAL: litellm not healthy ($h)" >&2; exit 1; }
done

# ---------------------------------------------------------------------------
log "7. virtual keys (honcho + hermes) + hermes-key model allowlist"
MK="$LITELLM_MASTER_KEY"
gen_key() {
  docker run --rm --network aitools-net curlimages/curl -s -X POST \
    http://aitools-litellm:4000/key/generate \
    -H "Authorization: Bearer $MK" -H "Content-Type: application/json" \
    -d "{\"key_alias\":\"$1\",\"models\":$2}" \
  | python3 -c "import sys,json;print(json.load(sys.stdin)['key'])"
}
HONCHO_MODELS='["glm-4.7-flash","grok-4.3","glm-5","voyage-4-lite","voyage-4-large","voyage-4","voyage-code-3","voyage-finance-2","voyage-law-2"]'
# Hermes agent brain = chatgpt/* (streaming) + glm/grok fallback. NEVER give
# Honcho chatgpt/* (its deriver/dream/dialectic calls are non-streaming — see
# README gotcha #5).
HERMES_MODELS='["chatgpt/gpt-5.5","chatgpt/gpt-5.4","chatgpt/gpt-5.4-mini","chatgpt/gpt-5.3-codex","chatgpt/gpt-5.3-codex-spark","glm-4.7-flash","grok-4.3","glm-5"]'
HONCHO_VIRTUAL_KEY="$(gen_key honcho "$HONCHO_MODELS")"
HERMES_VIRTUAL_KEY="$(gen_key hermes  "$HERMES_MODELS")"
cat > "$KEYS" <<EOF
HONCHO_VIRTUAL_KEY=$HONCHO_VIRTUAL_KEY
HERMES_VIRTUAL_KEY=$HERMES_VIRTUAL_KEY
EOF
echo "wrote $KEYS (gitignored)"
# Make the hermes key explicit via /key/update (idempotent allowlist expand).
docker run --rm --network aitools-net curlimages/curl -s -X POST \
  http://aitools-litellm:4000/key/update \
  -H "Authorization: Bearer $MK" -H "Content-Type: application/json" \
  -d "{\"key\":\"$HERMES_VIRTUAL_KEY\",\"models\":$HERMES_MODELS}" >/dev/null \
  && echo "hermes key model allowlist set"
# Honcho consumes its key from the env (compose passes HONCHO_VIRTUAL_KEY).
grep -q '^HONCHO_VIRTUAL_KEY=' "$SV_ENV" \
  && sed -i.bak "s|^HONCHO_VIRTUAL_KEY=.*|HONCHO_VIRTUAL_KEY=$HONCHO_VIRTUAL_KEY|" "$SV_ENV" \
  || echo "HONCHO_VIRTUAL_KEY=$HONCHO_VIRTUAL_KEY" >> "$SV_ENV"
rm -f "$SV_ENV.bak"

# ---------------------------------------------------------------------------
log "8. Honcho fresh-DB init (venv python, NOT uv run) + 1024 embedding dims"
# entrypoint runs alembic upgrade -> schema lands at the hardcoded 1536.
dc "$SV_ENV" -f aitools-services/compose.yaml up -d aitools-honcho-api aitools-honcho-deriver
for i in $(seq 1 36); do
  h=$(docker inspect -f '{{.State.Health.Status}}' aitools-honcho-api 2>/dev/null || echo none)
  [ "$h" = healthy ] && { echo "honcho-api healthy (alembic ran)"; break; }
  sleep 5
  [ "$i" = 36 ] && echo "WARN: honcho-api not healthy yet ($h) — continuing to dim fix"
done
# Alter pgvector columns 1536 -> 1024 using the IN-IMAGE venv interpreter.
# uv run rebuilds the project in-image and fails — use /app/.venv/bin/python.
dc "$SV_ENV" -f aitools-services/compose.yaml run --rm \
  --entrypoint /app/.venv/bin/python \
  aitools-honcho-api scripts/configure_embeddings.py --yes
# Recreate honcho so the boot embedding_validator passes (1024 == 1024).
dc "$SV_ENV" -f aitools-services/compose.yaml up -d --force-recreate \
  aitools-honcho-api aitools-honcho-deriver
for i in $(seq 1 36); do
  h=$(docker inspect -f '{{.State.Health.Status}}' aitools-honcho-api 2>/dev/null || echo none)
  [ "$h" = healthy ] && { echo "honcho-api healthy (validator passed @1024)"; break; }
  sleep 5
  [ "$i" = 36 ] && { echo "FATAL: honcho-api unhealthy after dim fix ($h)" >&2; exit 1; }
done

# ---------------------------------------------------------------------------
log "9. verify"
pgq() { docker run --rm --network aitools-net -e PGPASSWORD="$2" postgres:18 \
          psql -h aitools-pg -U "$1" -d "$1" -tAc "$3"; }
echo -n "pg version: "; pgq postgres "$(grep '^POSTGRES_SUPERPASS=' "$BK_ENV"|cut -d= -f2-)" "SELECT version();" 2>/dev/null | head -1 || true
echo -n "honcho role login: "; pgq honcho "$HONCHO_DB_PASSWORD" "SELECT 'ok';"
echo -n "litellm role login: "; pgq litellm "$LITELLM_DB_PASSWORD" "SELECT 'ok';"
echo -n "embedding column types: "
pgq honcho "$HONCHO_DB_PASSWORD" \
  "SELECT string_agg(format_type(atttypid,atttypmod),',') FROM pg_attribute WHERE attname='embedding' AND attrelid::regclass::text IN ('documents','message_embeddings');"
echo -n "litellm spend log rows: "
pgq litellm "$LITELLM_DB_PASSWORD" 'SELECT count(*) FROM "LiteLLM_SpendLogs";'

echo
echo "build-stack.sh DONE. aitools-* up. Next: ./build-hermes.sh <fresh-machine-name>"
