// compose.ts — render .stack/docker-compose.yaml.
//
// Just an `include:` block listing services/<svc>/compose.yaml for every
// <svc> in stackProfiles (COMPOSE_PROFILES closed under SERVICE_REQUIRES).
//
// Lives at .stack/docker-compose.yaml so the whole stack state is
// self-contained in one directory (easy to back up, easy to rm -rf for
// a clean slate). The include: paths are emitted relative to that
// location (../services/<svc>/…).
import { existsSync, writeFileSync, mkdirSync, renameSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { stringify as yamlStringify } from 'yaml'
import { STACK_ROOT, STACK_DIR } from './paths.ts'
import { stackProfiles } from './compose-env.ts'

export const COMPOSE_PATH = resolve(STACK_DIR, 'docker-compose.yaml')

export const renderCompose = (): void => {
  mkdirSync(dirname(COMPOSE_PATH), { recursive: true })
  const enabled = new Set(
    stackProfiles()
      .split(',')
      .map((x) => x.trim())
      .filter(Boolean),
  )
  const includes: string[] = []
  for (const svc of enabled) {
    const svcCompose = resolve(STACK_ROOT, 'services', svc, 'compose.yaml')
    if (!existsSync(svcCompose)) continue
    includes.push(relative(dirname(COMPOSE_PATH), svcCompose))
  }
  const includeYaml = includes.length ? yamlStringify({ include: includes }) : 'include: []\n'
  const body =
    '# GENERATED by lib/compose.ts — regenerated by stack-cli enable / disable /\n' +
    '# build / start (and by dc() as a safety net). Do not edit.\n' +
    '# Source of truth: COMPOSE_PROFILES in .stack/.env.\n' +
    includeYaml
  const tmp = COMPOSE_PATH + '.tmp'
  writeFileSync(tmp, body)
  renameSync(tmp, COMPOSE_PATH)
}
