// compose.ts — render .stack-node/docker-compose.yaml.
//
// Mirrors stack_render_compose() in lib/stacklib.sh:
//   - Header: the tracked docker-compose.example.yaml (comments only).
//   - Generated `include:` block listing services/<svc>/compose.yaml for
//     every <svc> in stack_profiles (COMPOSE_PROFILES closed under
//     SERVICE_REQUIRES).
//
// Lives at .stack-node/docker-compose.yaml so the whole stack state is
// self-contained in one directory (easy to back up, doesn't collide with
// the existing /docker-compose.yaml from the bash system). The include:
// paths are emitted relative to that location (../services/<svc>/…).
import { existsSync, readFileSync, writeFileSync, mkdirSync, renameSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { stringify as yamlStringify } from "yaml";
import { STACK_ROOT, STACK_DIR } from "./paths.ts";
import { stackProfiles } from "./compose-env.ts";

export const COMPOSE_PATH = resolve(STACK_DIR, "docker-compose.yaml");
const HEADER_PATH = resolve(STACK_ROOT, "docker-compose.example.yaml");

export const renderCompose = (): void => {
  mkdirSync(dirname(COMPOSE_PATH), { recursive: true });
  const header = existsSync(HEADER_PATH) ? readFileSync(HEADER_PATH, "utf8") : "";
  const enabled = new Set(stackProfiles().split(",").map((x) => x.trim()).filter(Boolean));
  const includes: string[] = [];
  for (const svc of enabled) {
    const svcCompose = resolve(STACK_ROOT, "services", svc, "compose.yaml");
    if (!existsSync(svcCompose)) continue;
    includes.push(relative(dirname(COMPOSE_PATH), svcCompose));
  }
  const includeYaml = includes.length
    ? yamlStringify({ include: includes })
    : "include: []\n";
  const body =
    header +
    "\n# >>> GENERATED by lib/compose.ts. Do not edit; regenerated by\n" +
    "# >>> stack-cli enable/disable/build/start (and by dc() as a safety net).\n" +
    "# >>> Source of truth: docker-compose.example.yaml + COMPOSE_PROFILES.\n" +
    includeYaml +
    "# <<< GENERATED\n";
  const tmp = COMPOSE_PATH + ".tmp";
  writeFileSync(tmp, body);
  renameSync(tmp, COMPOSE_PATH);
};
