// services/mission-control/src/schemas/projects.ts
//
// Browser-safe schemas for /v1/projects. ONLY imports allowed: zod + ./common.ts.
//
// Mirrors src/routes/projects.ts exactly. Slug uniqueness is enforced per-org by
// the partial unique index `projects_slug_per_org_active`.
import { z } from 'zod';
import { IdSlug, IsoTimestamp, SoftDeleteFields } from './common.ts';

// ---------------------------------------------------------------------------
// Request bodies — mirror the inline `createSchema` (and its `.partial()`
// derivative `patchSchema`) in src/routes/projects.ts.
//
// Slug max length matches the route's regex+length (max 64, NOT 100).
// ---------------------------------------------------------------------------

const SLUG = z.string().regex(/^[a-z0-9-]+$/).min(1).max(64);

export const ProjectCreateBody = z.object({
  name: z.string().min(1).max(200),
  slug: SLUG,
  description: z.string().max(2000).optional(),
});
export type ProjectCreateBody = z.infer<typeof ProjectCreateBody>;

/**
 * PATCH body. Generated by `createSchema.partial()` in the route, so every field
 * is optional but `description`, when present, must still be a string (NOT
 * nullable — projects.ts differs from agents.ts/connectors.ts here).
 */
export const ProjectPatchBody = z.object({
  name: z.string().min(1).max(200).optional(),
  slug: SLUG.optional(),
  description: z.string().max(2000).optional(),
});
export type ProjectPatchBody = z.infer<typeof ProjectPatchBody>;

// ---------------------------------------------------------------------------
// Query params for GET /v1/projects.
// ---------------------------------------------------------------------------

export const ProjectListQuery = z.object({
  cursor: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).optional(),
});
export type ProjectListQuery = z.infer<typeof ProjectListQuery>;

// ---------------------------------------------------------------------------
// Project row — serializeTimestamps() output of src/db/pool.ts `projects`.
// No `last_seen_at` column (projects aren't principals).
// ---------------------------------------------------------------------------

export const Project = z
  .object({
    id: IdSlug('prj_'),
    org_id: z.string(),
    name: z.string(),
    slug: z.string(),
    description: z.string().nullable(),
    created_by_user_id: z.string().nullable(),
    created_at: IsoTimestamp,
    updated_at: IsoTimestamp,
  })
  .extend(SoftDeleteFields.shape);
export type Project = z.infer<typeof Project>;

// ---------------------------------------------------------------------------
// Response wrappers.
// ---------------------------------------------------------------------------

/** GET /v1/projects → `{ projects, next_cursor }` (NOT the generic `data` wrapper). */
export const ProjectListResponse = z.object({
  projects: z.array(Project),
  next_cursor: z.string().nullable(),
});
export type ProjectListResponse = z.infer<typeof ProjectListResponse>;

/** POST /v1/projects → `{ project }` (201). No raw key — projects aren't principals. */
export const ProjectCreateResponse = z.object({
  project: Project,
});
export type ProjectCreateResponse = z.infer<typeof ProjectCreateResponse>;

/** GET /v1/projects/:id and PATCH /v1/projects/:id → `{ project }`. */
export const ProjectDetailResponse = z.object({
  project: Project,
});
export type ProjectDetailResponse = z.infer<typeof ProjectDetailResponse>;

/** DELETE /v1/projects/:id → `{}` (200). */
export const ProjectDeleteResponse = z.object({}).strict();
export type ProjectDeleteResponse = z.infer<typeof ProjectDeleteResponse>;
